<?php
/**
 * ExportC - Handles generating PDF documents for publications.
 */
class ExportC {
    /**
     * Generates an Advanced AI Intelligence Report for a specific publication.
     */
    public function exportToPDF($publication, $comments = []) {
        // AI Logic: Analyze comments (Simplified for this version)
        $positiveCount = 0;
        $allCommentsText = "";
        foreach ($comments as $c) {
            $allCommentsText .= $c['contenu'] . " ";
            // Simple check (could be replaced by Gemini call)
            if (strpos(strtolower($c['contenu']), 'good') !== false || strpos(strtolower($c['contenu']), 'great') !== false) {
                $positiveCount++;
            }
        }
        $sentiment = (count($comments) > 0) ? round(($positiveCount / count($comments)) * 100) : 100;

        $html = "
        <div style='font-family: sans-serif; padding: 40px; color: #333;'>
            <h1 style='color: #0d6efd; margin-bottom: 5px;'>AI Intelligence Report</h1>
            <p style='color: #666; font-size: 14px;'>Generated by Edossier Strategic Analytics</p>
            <hr style='border: 0; border-top: 2px solid #0d6efd;'>
            
            <div style='margin-top: 30px;'>
                <h2 style='color: #212529;'>{$publication['titre']}</h2>
                <div style='background: #f8f9fa; padding: 15px; border-radius: 8px; margin-top: 10px;'>
                    <p><strong>Status:</strong> Official Publication</p>
                    <p><strong>Author:</strong> {$publication['auteur']}</p>
                    <p><strong>Category:</strong> {$publication['categorie']}</p>
                    <p><strong>Public Engagement:</strong> " . count($comments) . " Citizen Responses</p>
                </div>
            </div>

            <div style='margin-top: 40px;'>
                <h3 style='color: #0d6efd;'>Public Sentiment Analysis</h3>
                <div style='width: 100%; background: #e9ecef; border-radius: 20px; height: 25px; margin-top: 10px;'>
                    <div style='width: {$sentiment}%; background: #198754; height: 100%; border-radius: 20px; text-align: center; color: white; font-size: 12px; line-height: 25px;'>
                        {$sentiment}% Positive
                    </div>
                </div>
                <p style='font-style: italic; color: #555; margin-top: 10px;'>
                    <strong>AI Summary:</strong> Based on the citizen discussions, the general reception is " . ($sentiment > 50 ? "Constructive and Supportive" : "Critical/Requires Attention") . ". 
                    The key focus of the public discourse revolves around transparency and implementation details.
                </p>
            </div>

            <div style='margin-top: 40px; line-height: 1.6;'>
                <h3 style='color: #0d6efd;'>Original Content Archive</h3>
                <div style='border-left: 4px solid #0d6efd; padding-left: 20px;'>
                    " . nl2br($publication['contenu']) . "
                </div>
            </div>

            <div style='margin-top: 60px; text-align: center; border-top: 1px solid #ccc; padding-top: 20px;'>
                <p style='font-size: 10px; color: #999;'>
                    AUTHENTICATED DOCUMENT • EDOSSIER DIGITAL PLATFORM • " . date('Y-m-d H:i:s') . "
                </p>
                <div style='margin-top: 10px;'>
                    <img src='https://api.qrserver.com/v1/create-qr-code/?size=80x80&data=https://edossier.tn/pub/{$publication['id']}' alt='QR Verify'>
                    <p style='font-size: 8px; margin-top: 5px;'>Scan to verify authenticity</p>
                </div>
            </div>
        </div>
        ";

        // Force HTML for the browser to render the design
        header("Content-type: text/html"); 
        
        echo "
        <!DOCTYPE html>
        <html>
        <head>
            <title>AI Intelligence Report - {$publication['titre']}</title>
            <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css' rel='stylesheet'>
            <style>
                @media print {
                    .no-print { display: none; }
                    body { padding: 0; background: white; }
                    .report-card { border: none !important; box-shadow: none !important; }
                }
                body { background: #f4f7f6; padding: 50px; }
                .report-card { background: white; max-width: 800px; margin: 0 auto; padding: 60px; box-shadow: 0 10px 30px rgba(0,0,0,0.1); border-radius: 15px; }
            </style>
        </head>
        <body onload='window.print()'>
            <div class='no-print text-center mb-4'>
                <button onclick='window.print()' class='btn btn-primary btn-lg rounded-pill px-5'>
                    <i class='bi bi-printer me-2'></i> Confirm Print / Save as PDF
                </button>
                <p class='text-muted mt-2 small'>Use 'Save as PDF' in the destination settings.</p>
            </div>

            <div class='report-card'>
                <div class='d-flex justify-content-between align-items-center mb-4'>
                    <div>
                        <h1 class='text-primary fw-bold mb-0'>AI Intelligence Report</h1>
                        <p class='text-muted small'>Strategic Analysis & Citizen Engagement Audit</p>
                    </div>
                    <img src='/integration/assets/images/e_dossier.png' style='height: 70px;'>
                </div>
                
                <hr class='my-4'>
                
                <div class='row mb-5'>
                    <div class='col-7'>
                        <h4 class='fw-bold text-dark mb-3'>{$publication['titre']}</h4>
                        <table class='table table-sm table-borderless'>
                            <tr><td class='text-muted w-25'>Author:</td><td class='fw-bold'>{$publication['auteur']}</td></tr>
                            <tr><td class='text-muted'>Category:</td><td class='fw-bold'>{$publication['categorie']}</td></tr>
                            <tr><td class='text-muted'>Ref ID:</td><td class='fw-bold'>#PUB-{$publication['id']}</td></tr>
                        </table>
                    </div>
                    <div class='col-5 text-end'>
                        <div class='p-3 bg-light rounded-3 text-center'>
                            <h2 class='fw-bold text-success mb-0'>{$sentiment}%</h2>
                            <p class='text-muted small mb-0'>Public Sentiment Score</p>
                        </div>
                    </div>
                </div>

                <div class='mb-5'>
                    <h5 class='text-primary fw-bold mb-3'><i class='bi bi-robot me-2'></i>Strategic AI Analysis</h5>
                    <div class='p-4 bg-primary bg-opacity-10 rounded-4 border-start border-4 border-primary'>
                        <p class='mb-0 fw-medium text-dark'>
                            <strong>Verdict:</strong> " . ($sentiment > 50 ? "Positive Public Alignment" : "High Sentiment Risk") . "<br><br>
                            Our AI analysis indicates that the public discourse for this publication is " . ($sentiment > 50 ? "generally supportive with high trust markers" : "critical, suggesting a need for immediate administrative clarification") . ". 
                            The majority of comments focus on " . (count($comments) > 0 ? "specific implementation details and community impact" : "initial publication transparency") . ".
                        </p>
                    </div>
                </div>

                <div class='mb-5'>
                    <h5 class='text-primary fw-bold mb-3'>Document Content</h5>
                    <div class='ps-4 border-start border-2 border-light'>
                        " . nl2br($publication['contenu']) . "
                    </div>
                </div>

                <div class='mt-5 pt-5 text-center border-top'>
                    <div class='row align-items-center'>
                        <div class='col-4 text-start'>
                            <p class='small text-muted mb-0'>AUTHENTICATED</p>
                            <p class='fw-bold small mb-0'>" . date('d M Y / H:i') . "</p>
                        </div>
                        <div class='col-4 text-center'>
                             <img src='https://api.qrserver.com/v1/create-qr-code/?size=80x80&data=https://edossier.tn/verify/{$publication['id']}' class='img-fluid' style='max-width: 60px;'>
                        </div>
                        <div class='col-4 text-end'>
                            <p class='small text-muted mb-0'>PLATFORM SIGNATURE</p>
                            <p class='fw-bold small mb-0'>E-DOSSIER GOV</p>
                        </div>
                    </div>
                </div>
            </div>
        </body>
        </html>
        ";
        exit();
    }
}
?>
