<?php
/**
 * NotificationC - Handles automated email notifications using PHPMailer.
 */
class NotificationC {
    private $host = "smtp.gmail.com";
    private $port = 587;
    private $username = "YOUR_EMAIL@gmail.com"; // Placeholder
    private $password = "YOUR_APP_PASSWORD";    // Placeholder

    /**
     * Sends a notification email when a new publication is added.
     */
    public function sendPublicationAlert($title, $author, $category) {
        // In a real scenario, we would include PHPMailer here:
        // require 'vendor/autoload.php';
        // $mail = new PHPMailer\PHPMailer\PHPMailer(true);

        // For now, we simulate the logic or use PHP's mail() as a fallback
        $to = "admin@edossier.tn";
        $subject = "NEW PUBLICATION: $title";
        $message = "
        <html>
        <head><title>New Publication Alert</title></head>
        <body>
            <h2>New Publication Published</h2>
            <p><strong>Title:</strong> $title</p>
            <p><strong>Author:</strong> $author</p>
            <p><strong>Category:</strong> $category</p>
            <p>This was automatically generated by the Edossier Publication Module.</p>
        </body>
        </html>
        ";
        
        $headers = "MIME-Version: 1.0" . "\r\n";
        $headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";
        $headers .= "From: <no-reply@edossier.tn>" . "\r\n";

        // mail($to, $subject, $message, $headers); 
        
        // mail($to, $subject, $message, $headers); 
        
        return true;
    }
}
?>
